[package]
name = "hook-test"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
amethyst = "0.10.0"
serde = { version = "1.0", features = ["derive"] }
num-traits = "0.2"
num-derive = "0.2"